project_id = "kzyfwsisfxveibsgudlm"

[functions.analyze-ingredients]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.link-device-subscription]
verify_jwt = false